### ISSUE TITLE
Localhost image generating

### ISSUE THREAD

**Issue by f3l1x** [dotblue/nette-webimages#10]
I have XAMMP and URL for example localhost/webimages/www and path for images is storage/<path>. 

It makes folders in storage, localhost/webimages/www/webimages/www/storage/mypicture-100x100.jpg. 

It can be fixed by replacing basePath in URL. I could send PR.

**Comment by vojtech-dobes** [comment]
@f3l1x Would you please send PR :) ?

**Comment by f3l1x** [comment]
I think it's ok. I check it later.
