### ISSUE TITLE
Resizing image in provider

### ISSUE THREAD

**Issue by Lawondyss** [dotblue/nette-webimages#13]
Why not create thumbnails in the provider? The provider generate only path to the picture, but I want to have in control the method of obtaining thumbnails.

**Comment by vojtech-dobes** [comment]
I am not sure I follow.

**Comment by vysinsky** [comment]
You can do whatever you want in provider. See https://github.com/dotblue/nette-webimages/blob/master/examples/DefaultImageProvider.php

**Comment by Lawondyss** [comment]
OK, but why Generator save image from Provider?
https://github.com/dotblue/nette-webimages/blob/master/src/Generator.php#L88

**Comment by vysinsky** [comment]
Because the main goal of this library is that you process image only once.

When you access /images/dog.jpg and it does not exist it fires the provider which returns image and this images is saved to location /images/dog.jpg

Next time someonte access /images/dog.jpg the provider (whole nette application) is not called at all because web server returns it immediately.

**Comment by Lawondyss** [comment]
And why not save the image in the provider?

**Comment by vysinsky** [comment]
Why would you do that? It would be the same code in every provider. Provider does not care where it will be saved or if it will be saved at all. Provider just returns image in exact format.

**Comment by Lawondyss** [comment]
Because I cannot over save the image.
**Example:**
I have two provider. First return thumbnail from expected picture. Second return placeholder if expected picture not exist. If Generator save the placeholder, then first provider never save new picture when expected picture already exists.

**Comment by Lawondyss** [comment]
BTW sorry for the bad title of the Issue.

**Comment by vojtech-dobes** [comment]
Well, if picture exists and it's requested for the first time, it will generate and save thumbnail. If it doesn't exist, placeholder will be saved instead. If you get the image later and you want to change placeholder to correctly generated thumbnail, you can either: 1) delete the current thumbnail 2) save the image under new name.

**Comment by Lawondyss** [comment]
OK, thanks. I suppose you not change your opinion about moving deciding of saving to a provider.

**Comment by vojtech-dobes** [comment]
> I suppose you not change your opinion about moving deciding of saving to a provider.

Well, why should I :) ? At this moment, without further arguments, I think it would break the whole architecture (it just wouldn't make any sense).

**Comment by vysinsky** [comment]
@vojtech-dobes :+1:

**Comment by Lawondyss** [comment]
Tak Ahoj Michale a RT to
